# Generated by Django 5.2.4 on 2025-07-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_bank_bank_name_alter_bank_swift_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
    ]
