# Generated by Django 5.2.4 on 2025-07-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_bank_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
