# Generated by Django 5.2.4 on 2025-07-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
