# Generated by Django 5.2.4 on 2025-07-31 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_remove_employee_branch_attachment_delete_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='Employee_is_dele_e4d938_idx',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='contracttype',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='employeecustomfieldconfig',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='fieldtype',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='jobtitle',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.RenameField(
            model_name='phonecountrycode',
            old_name='is_deleted',
            new_name='deleted',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['deleted'], name='Employee_deleted_55808d_idx'),
        ),
    ]
